name: auto set pull request to draft on new commit

on:
  pull_request:
    types:
      - synchronize

jobs:
  set-draft:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: generate github app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set pull request to draft
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr ready $PR_NUMBER --undo
          echo "pull request #$PR_NUMBER has been set to draft."
